/* HOME3.C

:Homing routine using the combined home and index logic 

This sample demonstrates a basic homing algorithm.  The home location is found
 based on the home and index input logic.
 
Here is the algorithm:
 1) Velocity move towards the home input anded with the index.
 2) Zero the position at the home and index pulse
 	(New Frame Event generated by DSP).
 3) Stop the axis.
 4) Move to the home position.

Here is the sensor logic:
 Home input = active high
 Index input = active high

Warning!  This is a sample program to assist in the integration of the
 DSP-Series controller with your application.  It may not contain all 
 of the logic and safety features that your application requires.
  
Written for Version 2.5  
*/

/*  Revision Control System Information
	$Source$ 
	$Revision$
	$Date$

	$Log$
	Revision 1.1  1999/08/31 16:43:08  briegel
	source for MEI library

*/

# include <stdio.h>
# include <stdlib.h>
# include <conio.h>   
# include "pcdsp.h"

# define AXIS		0
# define VELOCITY	500.0
# define ACCEL		10000.0

void error(int16 error_code)
{   
	char buffer[MAX_ERROR_LEN];

	switch (error_code)
	{
		case DSP_OK:
			/* No error, so we can ignore it. */
			break ;

		default:
			error_msg(error_code, buffer) ;
			fprintf(stderr, "ERROR: %s (%d).\n", buffer, error_code) ;
			exit(1);
			break;
	}
}

void display(int16 axis)
{
	int16 home_logic, state;
	double cmd;
	
	while (!motion_done(axis))
	{	get_command(axis, &cmd);
		printf("\rCmd: %10.0lf Home Logic: %d", cmd, home_switch(AXIS));	
	
		if (kbhit())
		{	getch();
			exit(1);
		}	
	}
	printf("\n");
}

int16 main()
{
	int16 error_code;
	
	error_code = do_dsp();	/* initialize communication with the controller */
	error(error_code);		/* any problems initializing? */
	
	/* make sure no events are generated during home logic configuration */
	set_home(AXIS, NO_EVENT);
	error(clear_status(AXIS));
	
	set_stop_rate(AXIS, ACCEL);
	set_home_index_config(AXIS, HIGH_HOME_AND_INDEX);
	set_home_level(AXIS, FALSE);
   
	printf("\nSearching for home and index. (Press any key to quit)\n");
	v_move(AXIS, VELOCITY, ACCEL);		/* velocity move towards home sensor */
	dsp_home_action(AXIS, NEW_FRAME);
	dsp_dwell(AXIS, 10000.0);			/* wait for New frame event */ 
	dsp_home_action(AXIS, NO_EVENT);
	set_position(AXIS, 0.0);			/* zero command and actual position */
	v_move(AXIS, 0.0, ACCEL);
	
	display(AXIS);
	
	start_move(AXIS, 0.0, VELOCITY, ACCEL);		/* move to home location */
	display(AXIS);
	printf("\nAxis is home.\n");

	return 0;
}
