/* HOME2.C

:Two stage homing routine using the home input

This sample demonstrates a basic homing algorithm.  The home location is found
 based on the home input.

Here is the algorithm:
 1) Fast velocity move towards the home sensor.
 2) Stop at the home sensor (Stop Event generated by DSP).
 3) Position move off the home sensor (opposite direction).
 4) Slow velocity move towards the home sensor.
 5) Stop at the home sensor (Stop Event generated by DSP).
 6) Zero the position.

Here is the sensor logic:
 Home input = active high
 Index input = not used

Warning!  This is a sample program to assist in the integration of the
 DSP-Series controller with your application.  It may not contain all 
 of the logic and safety features that your application requires.
  
Written for Version 2.5
*/

/*  Revision Control System Information
	$Source$ 
	$Revision$
	$Date$

	$Log$
	Revision 1.1  1999/08/31 16:43:07  briegel
	source for MEI library

*/

# include <stdio.h>
# include <stdlib.h>
# include <conio.h>   
# include "pcdsp.h"

# define AXIS		0
# define SLOW_VEL	200.0
# define FAST_VEL	20000.0
# define SLOW_ACCEL	10000.0
# define FAST_ACCEL	50000.0

void error(int16 error_code)
{
	char buffer[MAX_ERROR_LEN];

	switch (error_code)
	{
		case DSP_OK:
			/* No error, so we can ignore it. */
			break ;

		default:
			error_msg(error_code, buffer) ;
			fprintf(stderr, "ERROR: %s (%d).\n", buffer, error_code) ;
			exit(1);
			break;
	}
}

void display(int16 axis)
{
	int16 home_logic, state;
	double cmd;
	
	while (!motion_done(axis))
	{	get_command(axis, &cmd);
		printf("\rCmd: %10.0lf Home Logic: %d", cmd, home_switch(AXIS));	
	
		if (kbhit())
		{	getch();
			exit(1);
		}
	}
	printf("\n");
}

int16 main()
{
	int16 error_code;
	double distance;
	
	error_code = do_dsp();	/* initialize communication with the controller */
	error(error_code);		/* any problems initializing? */
	
	/* make sure no events are generated during home logic configuration */
	set_home(AXIS, NO_EVENT);
	error(clear_status(AXIS));
	
	set_stop_rate(AXIS, SLOW_ACCEL);
	set_home_index_config(AXIS, HOME_ONLY);
	set_home_level(AXIS, TRUE);
	set_home(AXIS, STOP_EVENT);

	printf("\nQuickly searching for home sensor. (Press any key to quit)\n");
	v_move(AXIS, FAST_VEL, SLOW_ACCEL);	/* velocity move towards home sensor */
	display(AXIS);

	set_home(AXIS, NO_EVENT);
	error(clear_status(AXIS));

	/* move off by a dist equal to twice the decel distance */
	distance = FAST_VEL * FAST_VEL / SLOW_ACCEL;
	start_r_move(AXIS, -distance, FAST_VEL, FAST_ACCEL);
	display(AXIS);

	printf("\nSlowly searching for home sensor. (Press any key to quit)\n");
	set_stop_rate(AXIS, FAST_ACCEL);
	set_home(AXIS, STOP_EVENT);
	v_move(AXIS, SLOW_VEL, FAST_ACCEL);
	display(AXIS);
	
	set_position(AXIS, 0.0);			/* zero command and actual position */
	printf("\nAxis is home.\n");

	return 0;
}
