int tm_move_time (int axis, int vel, int accel, int time);
int tm_move_pos (int axis, int vel, int accel, int pos);
int tm_bf (int axis, int vel, int accel, int pos1,int pos2, int times);
int tm_start_move (int axis, int vel, int accel, int pos);
void tm_set_coeffs(int axis, int index, int val);
void tm_print_coeffs(int axis);
void tm_display_axis(int axis);
void tm_nodisplay_axis(int axis);
void tm_display_continuous();
void tm_display_once();
void tm_display (int delay);
void tm_clear_pos (int axis);
void tm_set_sample_rate (unsigned short rate);
void tm_set_pos (int axis, int pos);
void tm_set_analog_encoder(int axis, int channel);
void tm_set_encoder(int axis);
void tm_controller_run (int axis);
void tm_controller_idle (int axis);
void tm_dual_loop (int axis, int dual);
void tm_set_boot_filter (int axis);
void tmDisplay (int delay);
void TM_help();
void tm_jog_axis();
void tm_az_brake_on();
void tm_az_brake_off();
int tm_az_brake(short val);
void tm_alt_brake_on();
void tm_alt_brake_off();
int tm_alt_brake(short val);
int tm_brake_status();
void tm_clamp_on();
void tm_clamp_off();
int tm_clamp(short val);
int tm_brake_status();
int tm_amp_disengage();
int tm_amp_engage();
int tm_setup_wd ();
void tm_print_axis_status(int axis);
void tm_print_axis_state(int axis);
void tm_print_axis_source(int axis);
